module Analysis

from "./ast.gr" include Ast
from "./infer.gr" include Infer
from "./types.gr" include Types
from "./lower.gr" include Lower
from "../frontend/parser.gr" include Parser

provide record Analysis {
  program: Ast.Program,
  infer: Infer.InferState,
}

provide let testLambda = () => {
  let source = "let id = (x) => {x};"
  print("Source: " ++ source)
  let parsed = Parser.parse(source)
  print("Parsed AST:")
  print(parsed)
}

testLambda()
